name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [Any CPU]

    runs-on: windows-latest

    env:
      Solution_Name: KadampaScreenSaver.sln
      Project_Directory: KadampaScreenSaver

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Project_Directory -ChildPath KadampaScreenSaver_TemporaryKey.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Extract version from csproj
      run: |
        $csprojPath = Join-Path -Path $env:Project_Directory -ChildPath "KadampaScreenSaver.csproj"
        $csproj = [xml](Get-Content $csprojPath)
        $version = $csproj.Project.PropertyGroup.Version
        echo "VERSION=$version" | Out-File -Append -FilePath $env:GITHUB_ENV
      shell: pwsh

    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform="${{ matrix.platform }}"
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish the application
      run: msbuild $env:Solution_Name /t:Publish /p:WindowsPackageType=None /p:Configuration=$env:Configuration /p:Platform="${{ matrix.platform }}"
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Create ZIP of unpackaged app
      run: Compress-Archive -Path "KadampaScreenSaver/bin/Release/net8.0/publish/*" -DestinationPath "KadampaScreenSaver/KadampaScreenSaver-${{ env.VERSION }}.zip"
  
    - name: Upload unpackaged app
      uses: actions/upload-artifact@v2
      with:
        name: KadampaScreenSaver-${{ env.VERSION }}.zip
        path: KadampaScreenSaver/KadampaScreenSaver-${{ env.VERSION }}.zip
